# #################################################################################################################
# ,---.    ,---.,---------.  _______               _______      ,-----.    ,---.   .--. ________ .-./`)   .-_'''-.
# |    \  /    |\          \\  ____  \            /   __  \   .'  .-,  '.  |    \  |  ||        |\ .-.') '_( )_   \
# |  ,  \/  ,  | `--.  ,---'| |    \ |           | ,_/  \__) / ,-.|  \ _ \ |  ,  \ |  ||   .----'/ `-' \|(_ o _)|  '
# |  |\_   /|  |    |   \   | |____/ /         ,-./  )      ;  \  '_ /  | :|  |\_ \|  ||  _|____  `-'`"`. (_,_)/___|
# |  _( )_/ |  |    :_ _:   |   _ _ '.         \  '_ '`)    |  _`,/ \ _/  ||  _( )_\  ||_( )_   | .---. |  |  .-----.
# | (_ o _) |  |    (_I_)   |  ( ' )  \         > (_)  )  __: (  '\_/ \   ;| (_ o _)  |(_ o._)__| |   | '  \  '-   .'
# |  (_,_)  |  |   (_(=)_)  | (_{;}_) |        (  .  .-'_/  )\ `"/  \  ) / |  (_,_)\  ||(_,_)     |   |  \  `-'`   |
# |  |      |  |    (_I_)   |  (_,_)  /         `-'`-'     /  '. \_/``".'  |  |    |  ||   |      |   |   \        /
# '--'      '--'    '---'   /_______.'            `._____.'     '-----'    '--'    '--''---'      '---'    `'-...-'
# ##################################################################################################################

source = ~/.config/hypr/bind.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/environment.conf

###################
### MY PROGRAMS ###
###################
$terminal = ghostty
$fileManager = dolphin
$menu = wofi --show drun
$menu = ulauncher-toggle
$browser = app.zen_browser.zen 

cursor {
	no_hardware_cursors = true
}

#####################
### LOOK AND FEEL ###
#####################
general { 
    gaps_in = 2
    # gaps_out = 5
    gaps_out = 5
    border_size = 0
    col.inactive_border = rgba(45475a88)
    col.active_border = rgba(45475a88)
    resize_on_border = false
    allow_tearing = true
    layout = dwindle
}


decoration {
    rounding = 22
    # active_opacity = 1.0
    # inactive_opacity = 1.0 

    # blur {
    #         enabled = true
    #         size = 6
    #         passes = 2
    #         vibrancy = 0.5
    #     }
    blur {
        enabled = true
        size = 3
        passes = 2
        vibrancy = 0.1696
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc { 
    force_default_wallpaper = 1
    disable_hyprland_logo = true
    vrr=0
}


#############
### INPUT ###
#############
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:swapescape
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
