
################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# Set DP-2 as the main center monitor
monitor=DP-2,1920x1080@239.5,0x0,1

# Set DP-1 to the right of DP-2
monitor=HDMI-A-1,1920x1080@60,1920x0,1

monitor = DP-1 , preferred, 1920x1080@60, 1, mirror, DP-2

# Bind workspace 1 to monitor 1
workspace=1,monitor:DP-2

# Bind workspace 2 to monitor 1
workspace=2,monitor:DP-2, orientation:top

# Bind workspace 3 to monitor 1
workspace=3,monitor:DP-2

# Bind workspace 4 to monitor 1
workspace=4,monitor:DP-2

# Bind workspace 5 to monitor 1
workspace = 5, monitor:DP-2, on-created-empty:thunderbird


# Bind workspace 6 and 7 to monitor 2
workspace=6,monitor:HDMI-A-1, on-created-empty:btop
workspace=7,monitor:HDMI-A-1

