##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = stayfocused,^(Ulauncher)$

windowrule {
  name = windowrule-1
  float = on
  no_initial_focus = on
  size = 600 400            # make the window bigger (width x height)
  move = ((monitor_w*1)-610) 50   # top-right: x offset from right edge, y offset from top
  pin = on
  animation = slide right
  match:title = (Picture-in-Picture)
}

# windowrule = opacity 0.89 override 0.89 override, class:.* 
windowrule {
  name = windowrule-2
  opacity = 0.9 0.9
  match:class = .*^(org.pwmt.zathura)$
}

windowrule = match:class clipse, float true # ensure you have a floating window class set if you want this behavior
windowrule = match:class clipse, size 622 652 # set the size of the window as necessary
windowrule {
  name = windowrule-3
  stay_focused = on
  match:class = ^(clipse)$
}

windowrule {
    name = ulauncher
    move = ((monitor_w)-window_w)*0.5 ((monitor_h)-window_h)*0.3
    border_size = 3
    border_color = rgba(fbfbfb35)
    stay_focused = on
    no_blur = on
    match:title = negative:Ulauncher Preferences
    match:class = ulauncher
}

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
windowrule {
  name = windowrule-4
  suppress_event = maximize
  match:class = .* # You'll probably like this.
}

# windowrule {
#   name = windowrule-5
#   float = on
#   border_size = 0
#   no_shadow = on
#   center = on
#   match:class = ^(ulauncher)$
# }


